@RootUrl = https://localhost:7289

### Auth
POST {{RootUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "moolie",
  "password": "moolie",
  "email": "moolie@gmail.com"
}

### Result
### {
#   "id": "019a3efd-8a62-7c8b-b2a1-fd3f3ec0b9af",
#   "username": "woolie",
#   "email": "woolie@gmail.com",
#   "passwordHash": "AQAAAAIAAYagAAAAEAvjacOlh6guhcHs6wjaD5Z+zYR5cuUOr8lBy1Av9XtRRHcORhH+Vdsv+HI4vbplqg==",
#   "role": "User",
#   "createdAt": "2025-11-01T10:36:34.6650465Z",
#   "refreshToken": null,
#   "refreshTokenExpiryTime": null,
#   "playerProfile": null,
#   "organizerProfile": null,
#   "personnelProfile": null
### }

### User
### GetUsers
GET {{RootUrl}}/api/User/
Accept: application/json

### GetById
GET {{RootUrl}}/api/User/29115d1b-b57a-4b41-a72d-4a9fbe6e4837
Accept: application/json

### Post
POST {{RootUrl}}/api/User
Content-Type: application/json

{
  "username": "Woolie",
  "email": "woolie@gmail.com",
  "passwordHash": "hashed_password",
  "type": "Player"
}
