
@RootUrl = https://localhost:7289
#
### User
### GetUsers
GET {{RootUrl}}/api/User/
Accept: application/json

### GetById
GET {{RootUrl}}/api/User/29115d1b-b57a-4b41-a72d-4a9fbe6e4837
Accept: application/json

### Post
POST {{RootUrl}}/api/User
Content-Type: application/json

{
  "username": "Woolie",
  "email": "woolie@gmail.com",
  "passwordHash": "hashed_password",
  "type": "Player"
}

POST {{RootUrl}}/api/User
Content-Type: application/json

{
  "username": "Woolie",
  "email": "woolie@gmail.com",
  "passwordHash": "hashed_password",
  "type": "Player"
}
